# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_vert = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_vert.setOrientation(QtCore.Qt.Vertical)
        self.splitter_vert.setObjectName("splitter_vert")
        self.splitter_horiz = QtWidgets.QSplitter(self.splitter_vert)
        self.splitter_horiz.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_horiz.setObjectName("splitter_horiz")
        self.scroll_plot = ScrollPlot(self.splitter_horiz)
        self.scroll_plot.setObjectName("scroll_plot")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_horiz)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.spinbox_elapsed_time = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_elapsed_time.sizePolicy().hasHeightForWidth())
        self.spinbox_elapsed_time.setSizePolicy(sizePolicy)
        self.spinbox_elapsed_time.setMinimumSize(QtCore.QSize(0, 0))
        self.spinbox_elapsed_time.setFrame(True)
        self.spinbox_elapsed_time.setReadOnly(True)
        self.spinbox_elapsed_time.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_elapsed_time.setKeyboardTracking(False)
        self.spinbox_elapsed_time.setProperty("showGroupSeparator", True)
        self.spinbox_elapsed_time.setDecimals(3)
        self.spinbox_elapsed_time.setMaximum(999999999999.0)
        self.spinbox_elapsed_time.setObjectName("spinbox_elapsed_time")
        self.gridLayout_2.addWidget(self.spinbox_elapsed_time, 0, 1, 1, 1)
        self.spinbox_num_points = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinbox_num_points.setFrame(True)
        self.spinbox_num_points.setReadOnly(True)
        self.spinbox_num_points.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_num_points.setKeyboardTracking(False)
        self.spinbox_num_points.setProperty("showGroupSeparator", True)
        self.spinbox_num_points.setMaximum(999999999)
        self.spinbox_num_points.setObjectName("spinbox_num_points")
        self.gridLayout_2.addWidget(self.spinbox_num_points, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.param_connect = QtWidgets.QPushButton(self.groupBox)
        self.param_connect.setObjectName("param_connect")
        self.verticalLayout.addWidget(self.param_connect)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.param_gate_time = QtWidgets.QComboBox(self.groupBox)
        self.param_gate_time.setObjectName("param_gate_time")
        self.horizontalLayout.addWidget(self.param_gate_time)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.param_set_gatetime = QtWidgets.QPushButton(self.groupBox)
        self.param_set_gatetime.setObjectName("param_set_gatetime")
        self.verticalLayout.addWidget(self.param_set_gatetime)
        self.param_toggle_power = QtWidgets.QPushButton(self.groupBox)
        self.param_toggle_power.setObjectName("param_toggle_power")
        self.verticalLayout.addWidget(self.param_toggle_power)
        self.param_toggle_acquisition = QtWidgets.QPushButton(self.groupBox)
        self.param_toggle_acquisition.setObjectName("param_toggle_acquisition")
        self.verticalLayout.addWidget(self.param_toggle_acquisition)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.display_time_box = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.display_time_box.setProperty("showGroupSeparator", False)
        self.display_time_box.setDecimals(1)
        self.display_time_box.setMaximum(3600.0)
        self.display_time_box.setObjectName("display_time_box")
        self.horizontalLayout_4.addWidget(self.display_time_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.clearplot_bttn = QtWidgets.QPushButton(self.groupBox_2)
        self.clearplot_bttn.setObjectName("clearplot_bttn")
        self.verticalLayout_3.addWidget(self.clearplot_bttn)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.buffer_size_box = QtWidgets.QSpinBox(self.groupBox_3)
        self.buffer_size_box.setMaximum(1000000)
        self.buffer_size_box.setObjectName("buffer_size_box")
        self.horizontalLayout_3.addWidget(self.buffer_size_box)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.mvavg_checkbox = QtWidgets.QGroupBox(self.layoutWidget)
        self.mvavg_checkbox.setCheckable(True)
        self.mvavg_checkbox.setChecked(False)
        self.mvavg_checkbox.setObjectName("mvavg_checkbox")
        self.gridLayout = QtWidgets.QGridLayout(self.mvavg_checkbox)
        self.gridLayout.setObjectName("gridLayout")
        self.mvavg_spinbox = QtWidgets.QSpinBox(self.mvavg_checkbox)
        self.mvavg_spinbox.setMinimum(1)
        self.mvavg_spinbox.setMaximum(100)
        self.mvavg_spinbox.setProperty("value", 10)
        self.mvavg_spinbox.setObjectName("mvavg_spinbox")
        self.gridLayout.addWidget(self.mvavg_spinbox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.mvavg_checkbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.mvavg_minmax_checkbox = QtWidgets.QCheckBox(self.mvavg_checkbox)
        self.mvavg_minmax_checkbox.setObjectName("mvavg_minmax_checkbox")
        self.gridLayout.addWidget(self.mvavg_minmax_checkbox, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.mvavg_checkbox)
        self.fft_push_bttn = QtWidgets.QPushButton(self.layoutWidget)
        self.fft_push_bttn.setObjectName("fft_push_bttn")
        self.verticalLayout_2.addWidget(self.fft_push_bttn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.dbg_console = QDbgConsole(self.splitter_vert)
        self.dbg_console.setObjectName("dbg_console")
        self.horizontalLayout_2.addWidget(self.splitter_vert)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BaLi Photon Counter"))
        self.label_6.setText(_translate("MainWindow", "Elapsed Time"))
        self.label_5.setText(_translate("MainWindow", "Saved Points"))
        self.groupBox.setTitle(_translate("MainWindow", "Options - Hardware"))
        self.param_connect.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "Gate Time"))
        self.param_set_gatetime.setText(_translate("MainWindow", "Set Gate Time"))
        self.param_toggle_power.setText(_translate("MainWindow", "Power ON"))
        self.param_toggle_acquisition.setText(_translate("MainWindow", "Start Acquisition"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Options - Graph"))
        self.label_3.setText(_translate("MainWindow", "Display time"))
        self.clearplot_bttn.setText(_translate("MainWindow", "Clear Plot"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Options - Software Buffer"))
        self.label_2.setText(_translate("MainWindow", "Buffer size"))
        self.mvavg_checkbox.setTitle(_translate("MainWindow", "Options - Moving Average"))
        self.label_4.setText(_translate("MainWindow", "Window size (# points)"))
        self.mvavg_minmax_checkbox.setText(_translate("MainWindow", "Show Minimum and Maximum"))
        self.fft_push_bttn.setText(_translate("MainWindow", "Open FFT window"))
from .qdbgconsole import QDbgConsole
from .scrollplot import ScrollPlot
